### ISSUE TITLE
webgpu headers need to be updated to include WGPURenderPassAttachment.depthSlice

### ISSUE THREAD

**Issue by AndrewAday** [eliemichel/WebGPU-distribution#14]
See https://github.com/gfx-rs/wgpu/issues/4764
and the [PR here](https://github.com/webgpu-native/webgpu-headers/pull/263/files#diff-074fca0467717d8d789bdfb86bf9e2d4afec03055a2787e0b604fda4254d4ed9)

Missing this field in the webgpu.h headers is causing device errors when running the emscripten build on web.

**Comment by AndrewAday** [comment]
As a temporary workaround, you can do:
```c
            WGPURenderPassColorAttachment colorAttachmentDesc = {};
#ifdef __EMSCRIPTEN__
            colorAttachmentDesc.depthSlice = WGPU_DEPTH_SLICE_UNDEFINED;
#endif
```

**Comment by eliemichel** [comment]
Since the API is always changing, each branch of this distribution repo contains precise git tag files telling which version of Dawn/wgpu-native/emscripten it was built for. The `webgpu.h` files that are shipped in this repo are never used when building with emscripten, so the problem you report has to be accounted for in the codebase that uses WebGPU rather than in this repo.

That being said, I noted this difference as well and the dev version of the guide [takes care of this](https://github.com/eliemichel/LearnWebGPU/blob/48dfae8876e0dff841935b01e621f315b2910735/next/getting-started/first-color.md?plain=1#L277) ;)
