### ISSUE TITLE
Swapchain gone missing

### ISSUE THREAD

**Issue by IgorAlexey** [eliemichel/WebGPU-distribution#18]
After updating to f2b8186, I lost reference to some specific types such as `Swapchain`, `SwapChainDescriptor`, `RenderPassDescriptor.timestampWriteCount`

Edit: I found [this issue](https://github.com/gfx-rs/wgpu/discussions/1910) but it seems to be very old? Why only now?

**Comment by eliemichel** [comment]
Hi! Since about 2 days, emscripten now supports the new Surface Configuration API. It was the last missing piece after wgpu-native and Dawn started supporting it as well, and the legacy SwapChain API is now deprecated. So I updates the first 8 chapters (the [Getting Started](https://eliemichel.github.io/LearnWebGPU/getting-started/index.html) section) and started upgrading the `main` branch here.

I would recommend that you do not try to follow the `main` tag when you set up a project but rather lock to a specific commit/tag name so that you do not suffer from breaking changes the the API (since WebGPU is not 1.0 yet). Your existing codebase should keep on working with the previous tag you were using (most probably `a13b496dda848eabe335b21ddef5f402545db553` or `main-v0.1.0`.

The only thing that could force you to update is a breaking change in web browsers, but for now `a13b496dda848eabe335b21ddef5f402545db553` still works as long as you compile with an old version of emscripten.

If you wish to upgrade, the change is actually quite straightforward because it is not spread across many things. It all boils down to what is described in the (new) [First Color](https://eliemichel.github.io/LearnWebGPU/getting-started/first-color.html) chapter:

 - Replace SwapChain creation by `surface.configure()` (a.k.a. `wgpuSurfaceConfigure()`
 - Getting the surface's **next texture** is a bit more verbose because you now get the whole texture and not just a texture view, so you may need to create a view yourself
 - Replace the swapchain presentation by a surface presentation

That's it mostly, plus a couple of other minor changes here and there that are not related to the SwapChain.

Let me know if you need further information!

**Comment by IgorAlexey** [comment]
Hi @eliemichel. Thanks so much for the explanation! The guidance on the new API and the recommendations have been very helpful!
