### ISSUE TITLE
Using emscripten webgpu.hpp with webgpu-raii.hpp causes compilation errors

### ISSUE THREAD

**Issue by PJayB** [eliemichel/WebGPU-distribution#39]
It looks like there is an inconsistency between the Dawn and Emscripten versions of `webgpu.hpp`: one uses `addRef`, the other uses `reference`, to increment the refcount.

This means that it is not currently possible to use the RAII wrappers on Emscripten:

```
WebGPU-raii/webgpu-raii.hpp:70:9: error: no member named 'addRef' in 'wgpu::Device'
   70 |                 m_raw.addRef();
```

**Comment by eliemichel** [comment]
There are numerous cases of mismatch these days, as all the breaking changes are happening prior to the upcoming v1 of the API. So it is important to stick to the very version of emscripten/dawn/wgpu-native that is marked in "txt" file next to your webgpu.hpp (if you're using this distribution repo).

The "AddRef" way is the latest standard, and most likely the one to remain on the long run. But Emscripten's lagging behind and may still use Release (and it probably depends on which version of emscripten), which is why I maintain different webgpu.hpp. I do not want to take initiatives and "adapt" emscripten API to the new standard before they do otherwise it'll make even more variants of versions around.

That being said, if your project needs to run with the same C++ codebase and using todays version of Dawn and emscripten, I'd suggest you to manually edit the `webgpu.hpp` that comes for your version of emscritpen so as to replace "release" by "addRef" and thus be able to write only "the dawn way" and have it adapted to (old) emscripten. The header is made such that this kind of change is easy enough: there is only the defininition of the `HANDLE` macro to change and it'll have effect on all objects.

Note that this will not be the only discrepancy you'll have to deal with. A possible other solution is to switch to [the fork of emscripten maintained by Dawn people](https://dawn.googlesource.com/dawn/+/refs/heads/main/src/emdawnwebgpu/), though I haven't tested it.

**Comment by PJayB** [comment]
Thanks for the advice! I'll modify the header for now.
